# CI de Nível 1 - Disparo manual
# TCC
name: "Disparo manual - Rodrigo Henrique"

on:
  workflow_dispatch:

# Permissões necessárias para que o dorny/test-reporter publique relatórios de teste
# - checks:write permite criar relatórios na aba "Checks" do GitHub
# - pull-requests:write permite comentar em pull requests (se necessário)
# - contents:read permite ler o conteúdo do repositório
permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  tests-with-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      # Executa os testes Mocha e gera relatório HTML visual com Mochawesome
      - name: Run Mocha tests (Mochawesome)
        run: yarn test:mochawesome

      # Faz upload do relatório HTML Mochawesome como artefato para download
      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: mochawesome-report/

  deploy:
    runs-on: ubuntu-latest
    needs: tests-with-reports
    steps:
      - name: Simulando deploy
        run: echo "Deploy do TCC efetuado com sucesso..."
