# CI de Nível 1 - Disparo manual
# TCC
name: "Disparo manual - Rodrigo Henrique"

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Install Playwright
        run: yarn playwright install

      - name: Run Mocha tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-e2e
          path: ./playwright-report

  tests-minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Run Mocha tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Simulando deploy
        run: echo "Simulating deployment..."
